#!/bin/bash
#  ██       ██                       
# ░██      ░██                       
# ░██      ░██ ███     ██ ██████████ 
# ░██████  ░██░░██  █ ░██░░██░░██░░██
# ░██░░░██ ░██ ░██ ███░██ ░██ ░██ ░██
# ░██  ░██ ░██ ░████░████ ░██ ░██ ░██
# ░██  ░██ ███ ███░ ░░░██ ███ ░██ ░██
# ░░   ░░ ░░░ ░░░    ░░░ ░░░  ░░  ░░ 
#nxll <nxll@teknik.io>

hc() {
    cmds="$cmds , $@"
}  

hc emit_hook reload

#REMOVE EXISTING BINDINGS
hc keyunbind --all

#KEYBINDINGS
Mod=Mod4     # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-q       reload
hc keybind $Mod-x       close

#TERMINAL
hc keybind $Mod-t spawn ${xterm:-urxvt} # use your $TERMINAL with xterm as fallback
#FILES
hc keybind $Mod-f spawn urxvt -e ranger
#WEB
hc keybind $Mod-w spawn firefox
#LAUNCHER
hc keybind $Mod-p spawn $HOME/bin/menu
#TOGGLE BAR
hc keybind $Mod-b spawn $HOME/bin/togglebar
#SCREENSHOT
hc keybind Print  spawn $HOME/bin/screenshot
#LOCKSCREEN
hc keybind XF86ScreenSaver spawn $HOME/bin/lock/lock.sh

#MEDIA CONTROL
hc keybind XF86AudioPlay spawn mpc toggle
hc keybind XF86AudioStop spawn mpc stop
hc keybind XF86AudioNext spawn mpc next
hc keybind XF86AudioPrev spawn mpc prev

#VOLUME CONTROL
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume @DEFAULT_SINK@ +5%
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume @DEFAULT_SINK@ +5% 
hc keybind XF86AudioMute        spawn pactl set-sink-mute @DEFAULT_SINK@ toggle

#FOCUS CLIENTS
hc keybind $Mod-Left   focus left
hc keybind $Mod-Down   focus down
hc keybind $Mod-Up     focus up
hc keybind $Mod-Right  focus right

#MOUSE OVER FOCUS
hc set focus_follows_mouse 1

#MOVE CLIENTS
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

#CREATE AN EMPTY FRAME
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5

#EXPLODE INTO SUBFRAMES
hc keybind $Mod-Control-space split explode

#RESIZE FRAMES
resizestep=0.05
hc keybind $Mod-Control-Left    resize left  +$resizestep
hc keybind $Mod-Control-Down    resize down  +$resizestep
hc keybind $Mod-Control-Up      resize up    +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

#TAGS
tag_names=( {TERM,CODE,WEB,DOC,MISC} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

#CYCLE TAGS
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

#LAYOUT
hc keybind $Mod-r           remove
hc keybind $Mod-space       floating toggle
hc keybind $Mod-Shift-space fullscreen toggle
hc keybind $Mod-Shift-p     pseudotile toggle
hc keybind $Mod-s     		cycle_layout +1 vertical horizontal grid

#MOUSE
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

#FOCUS
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c           cycle
hc keybind $Mod-i           jumpto urgent

#THEME
#hc attr theme.tiling.reset         1
#hc attr theme.floating.reset       1
hc set frame_border_active_color    '#21211F'
hc set frame_border_normal_color    '#21211F'
hc set frame_bg_normal_color        '#21211F'
hc set frame_bg_active_color        '#21211F'
hc set frame_border_width           0
hc set always_show_frame            0
hc set frame_bg_transparent         1
hc set frame_transparent_width      0
hc set frame_gap                    6
hc attr theme.active.color          '#A8A8A6'
hc attr theme.normal.color          '#262624'
hc attr theme.urgent.color          '#939490'
hc attr theme.inner_width           1
hc attr theme.outer_width           0
hc attr theme.inner_color           '#21211F'
hc attr theme.border_width          10
hc attr theme.floating.border_width 10
hc attr theme.floating.outer_width  0
hc attr theme.floating.inner_width  1
hc attr theme.floating.inner_color  '#21211F'
hc attr theme.floating.outer_color  '#21211F'
hc attr theme.active.inner_color    '#21211F'
hc attr theme.active.outer_color    '#21211F'
hc attr theme.normal.inner_color    '#21211F'
hc attr theme.normal.outer_color    '#21211F'
hc attr theme.background_color      '#21211F'  
hc set window_gap                   0
hc set frame_padding                0
hc set smart_window_surroundings    0
hc set smart_frame_surroundings     1
hc set mouse_recenter_gap           0

#RULES
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
#hc rule instance=gl  pseudotile=on

#UNLOCK
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

#monitor=${1:-0}
#herbstclient pad $monitor 16

# find the panel
panel=~/bin/bar
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

herbstclient chain $cmds&
