#!/bin/sh
#                                      ██
#  ██████                             ░██
# ░██░░░██  ██████   ███████   █████  ░██
# ░██  ░██ ░░░░░░██ ░░██░░░██ ██░░░██ ░██
# ░██████   ███████  ░██  ░██░███████ ░██
# ░██░░░   ██░░░░██  ░██  ░██░██░░░░  ░██
# ░██     ░░████████ ███  ░██░░██████ ███
# ░░       ░░░░░░░░ ░░░   ░░  ░░░░░░ ░░░ 
# For use with herbstluftwm
# Deps: herbstluftwm, lemonbar, iw, mpc, xtitle, pamixer (if using pulseaudio) 
# weechat notifications require hl2file.py

#pkill lemonbar

monitor=${1:-0}
herbstclient pad $monitor 16;

fg=FFFFFF
altfg=F0F0F0
bg=121314
altbg=191A1C
col1=151617
col2=AADB0F

#font="-lucy-tewii-medium-r-normal--11-90-100-100-c-60-iso10646-1"
#font="-gohu-gohufont-medium-r-normal--11-80-100-100-c-60-iso10646-1"
#font="-artwiz-drift-medium-r-normal--10-100-75-75-n-60-iso10646-1"
#font="-xos4-terminus-medium-r-normal--12-120-72-72-c-60-iso10646-1"
#font="-benis-lemon-medium-r-normal--*-*-75-75-m-*-iso10646-1"
font="-kakwa-kakwafont-medium-r-normal--12-120-72-72-c-60-iso8859-1"
glyphs="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"

height=16
borderwidth=0

muslength=50

clk()
{
    echo -n "%{B#$col1}  $(date "+%H:%M ")%{B-}"
}

dat()
{
    echo -n "%{B#$altbg}  $(date "+%B %d " | tr [A-Z] [a-z])%{B-}"
}

mus()
{
    music=$(mpc current -f "%artist% %{F#$altbg}≠%{F-} %title%")

    playing=$(mpc status | sed -n 2p | awk '{print $1}')
    if [ $playing = "[playing]" ] ; then
        symbol="%{B#$altbg}  %{B-}"
    elif [ $playing = "[paused]" ] ; then
        symbol="%{B#$altbg}  %{B-}"
    fi

    echo -n "${symbol}%{B#$col1} ${music} %{B-}"
}

#wchat()
#{   
#    symbol="%{B#$altbg}%{F#$fg}  %{F-}%{B-}"
#    
#    hilight=$(
#    if [ -s ~/.weechat/highlights.txt ] ; then
#       cat ~/.weechat/highlights.txt
#    else
#       echo -n "No MSG :("
#    fi)
#   
#    echo -n "${symbol} ${hilight}"
#}

#win()
#{
#    echo -n "%{B#$altbg}%{F#$fg}  %{F-}%{B-}"
#    echo -n "%{B#$col1}%{F#$fg} $(xtitle) %{F-}%{B-}"
#}

vol()
{
    percent=$(pamixer --get-volume)

    echo -n "%{B#$altbg}  %{B-} ${percent}%"
}

bat()
{
    percent=$(cat /sys/class/power_supply/BAT0/capacity)
    status=$(cat /sys/class/power_supply/BAT0/status)

    fullthing="${symbol} ${percent}"

    if test $status = "Charging"; then
        symbol=""
        echo -n "%{B#$altbg} ${symbol} %{B-} ${percent}%"
    elif test $status = "Full"; then
        symbol=""
        echo -n "%{B#$altbg} ${symbol} %{B-} ${percent}%"
    else
        if test $percent -gt 66; then
            symbol=""
            echo -n "%{B#$altbg} ${symbol} %{B-} ${percent}%"
        elif test $percent -gt 34; then
            symbol=""
            echo -n "%{B#$altbg} ${symbol} %{B-} ${percent}%"
        else
		symbol=""
            echo -n "%{B#$altbg} ${symbol} %{B-} ${percent}%"
        fi
    fi
}

net()
{
   symbol="%{B#$altbg}  %{B-}"
   wifi_ssid=$(
   if [ grep -q "Not connected."] ; then
      echo "No AP"
   else
      iw wls1 link | grep 'SSID' | sed 's/SSID: //' | sed 's/\t//'
   fi)

   echo -n "${symbol} ${wifi_ssid}"
}

wrk()
{
    TAGS=( $(herbstclient tag_status $monitor) )
    unset TAGS[${#TAGS[@]}]
    visible=true

    while true ; do
        echo -n "%{l}"
        for i in "${TAGS[@]}" ; do
            case ${i:0:1} in
                '#') # current tag
                    echo -n "%{F#$bg}%{B#$col2}"
                    ;;
                '+') # active on other monitor
                    echo -n "%{B#$altbg}"
                    ;;
                ':')
                    echo -n "%{F-}%{B#$altbg}"
                    ;;
                '!') # urgent tag
                    echo -n "%{B#$fg}"
                    ;;
                *)
                    echo -n "%{B-}%{F-}"
                    ;;
            esac
            echo -n " ${i:1} "
        done
        echo ""
        # wait for next event
        read line || break
        cmd=( $line ) 
        # find out event origin
        case "${cmd[0]}" in
            tag*)
                TAGS=( $(herbstclient tag_status $monitor) )
                unset TAGS[${#TAGS[@]}]
                ;;
            quit_panel)
                exit
                ;;
            reload)
                exit
                ;;
        esac
    done
}

floatbars()
{
 
    # add all the things
    while true; do
        buf="$(wrk)$(mus)%{r}$(bat) $(net) $(vol) $(dat)$(clk)" 
        echo $buf
        sleep 0.1
    done | lemonbar -f $glyphs \
        -f $font \
        -F \#$fg \
        -B \#$bg \
        -R \#$fg \
        -u 1 \
        -r $borderwidth \
        -g 1280x$height+0+0 | sh &
}

floatbars
