#!/bin/sh
#
#  ██                                                           
# ░██              ██████                                       
# ░██       ██████░██░░░██ ███     ██ ██████████  ██████  █████ 
# ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██░░██░░█ ██░░░██
# ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██ ░██ ░ ░██  ░░ 
# ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██ ░██   ░██   ██
# ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██░███   ░░█████ 
# ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░ ░░░     ░░░░░  
#

# Colors
bspc config normal_border_color "#151515"
bspc config focused_border_color "#111111"
bspc config presel_feedback_color "#181818"

# Borders
bspc config border_width         5
bspc config window_gap           8

# Lemonbar Padding
#bspc config bottom_padding 18

# Follow Mouse
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d TERM WEB APP DOX MISC
#bspc monitor -d I II III IV V

bspc rule -a Gimp state=floating follow=on
bspc rule -a MPlayer state=floating follow=on
bspc rule -a mpv state=floating follow=on
bspc rule -a Nitrogen state=floating follow=n
bspc rule -a Orage state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Skype state=floating
bspc rule -a dmenu_bind.sh focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a Chromium desktop=^2
# All Float
#bspc rule -a * state=floating
