#                                               /$$                        
#                                              | $$                        
#  /$$$$$$$  /$$$$$$  /$$$$$$/$$$$   /$$$$$$  /$$$$$$    /$$$$$$  /$$$$$$$ 
# /$$_____/ /$$__  $$| $$_  $$_  $$ /$$__  $$|_  $$_/   /$$__  $$| $$__  $$
#| $$      | $$  \ $$| $$ \ $$ \ $$| $$  \ $$  | $$    | $$  \ $$| $$  \ $$
#| $$      | $$  | $$| $$ | $$ | $$| $$  | $$  | $$ /$$| $$  | $$| $$  | $$
#|  $$$$$$$|  $$$$$$/| $$ | $$ | $$| $$$$$$$/  |  $$$$/|  $$$$$$/| $$  | $$
# \_______/ \______/ |__/ |__/ |__/| $$____/    \___/   \______/ |__/  |__/
#                                  | $$                                    
#                                  | $$                                    
#                                  |__/                                    

# SHADOWS
shadow-opacity = 0.5;
shadow-red = 0.0;
shadow-green = 0.0;
shadow-blue = 0.0;
shadow = true;
shadow-radius = 2;
shadow-offset-x = 2;
shadow-offset-y = 2;
no-dock-shadow = false;
no-dnd-shadow = true;
shadow-exclude = [
	"name = 'noshadow'",
	"class_g = 'maim'",
	"class_g = 'bar'"
];

# TRANSPARENT BORDERS
#frame-opacity=0.8;
frame-opacity=1.0;

# FADING
fading = true;
fade-in-step = 0.20;
fade-out-step = 0.20;
fade-exclude = [
	"name = 'bar'"
];

# BACKGROUND BLUR
#blur-background-fixed = true;
#blur-background-exclude = [
#    "window_type = 'dock'",
#    "window_type = 'desktop'"
#];

# OTHERS
use-ewmh-active-win = false
detect-client-opacity = true;
backend = "xrender"
detect-transient = true;
detect-client-leader = true;
shadow-ignore-shaped = true;
detect-rounded-corners = true;
